write_fields:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: ypsilon_local
    fields:
      required: true
      example: '{43: 50, 47: 400}'
      selector:
        object:

advance_phase:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: ypsilon_local
    phase:
      required: true
      selector:
        number:
          min: 0
          max: 4
          mode: box
